### ISSUE TITLE
Allow speaking of the street side name in maps

### ISSUE THREAD

**Issue by derekriemer** [josephsl/wintenApps#18]
Assign this to me if you'd like.
1. open maps and go click show my location, and then street side.
2. objnav to the map graphic.
3. drill in once.
4. If there's no street announced, tab until "Use keyboard to move to a different Streetside location" is announced.
5. Press up arrow.
6. objnav to one below the map.
7. keep trying until you see a street name.

I propose reading street names out as they change with cursor keys.

**Comment by josephsl** [comment]
Hi, have you discovered events we can catch? If it’s something NVDA doesn’t have, then a global plugin and an app module solution will be required. Happy to let you work on a PR for this. Thanks.

**Comment by josephsl** [comment]
No update for the last three yars, closing.
