### ISSUE TITLE
NVDA announces new incomming mails until I press the Control key

### ISSUE THREAD

**Issue by teaturkovic** [josephsl/wintenApps#23]
I'm using Windows 10 Creators ubdate, NVDA version 2017.1 and the last stable version of Winten App Essentials addon. Since the last addon ubdate, NVDA announces every new incomming mail until I press the Control key. Before downloading the last addon ubdate, everything worked well for me. I tried to restart NVDA and reload all addons again, but it didn't help.

**Comment by josephsl** [comment]
Hi, steps to reproduce please? Thanks.

**Comment by josephsl** [comment]
NO word from the original poster in three yars, closing.
