### ISSUE TITLE
Update check: What if other add-on is updating

### ISSUE THREAD

**Issue by nvdaes** [josephsl/wintenApps#27]
Updates aren't allowed while NVDA itself is updating. What if other add-on is updating at the same time?

**Comment by josephsl** [comment]
Hi, at the moment there’s no way to detect that other add-ons are getting updates (unless a custom window class name for add-on update dialogs are used and stays constant). This is something that would be resolved in NVDA Core issue 3208. Thanks.

**Comment by josephsl** [comment]
And indeed resolved via Add-on Updater. Closing.
