### ISSUE TITLE
Support for Developer Tools in Internet Explorer

### ISSUE THREAD

**Issue by sharkboyto** [josephsl/wintenApps#35]
Hi,
I'm an italian blind developer.
I use eclipse and notepad++ for more time.
In the front end application, I have the problem to debug or simple explore javascript file, add breackpoint and debug it.
After a lot of tools testing, browser testing and addons testing, for me, the best solution is to use the internet Explorer developer tools integrated in this browser.
There are a lot of hotkey at this page https://msdn.microsoft.com/en-us/library/dd565630(v=vs.85).aspx
The only problems are in the integrated editor, sometimes nvda lost the focus, and when go up or down in the editor, nvda read a not editor or source code info, but for example menus info or popup info.
For a developer, the js debug is a very important feature.

Is possible to fix it in the future version of App Essentials addon?

Thanks a lot.

**Comment by josephsl** [comment]
Hello, this is beyond the scope of this add-on. However, what you can try is file a bug with NVDA itself (github.com/nvaccess/nvda/issues/new) so NVDA developers can take a look at it. Thanks.
