### ISSUE TITLE
suggestion: please provide change log for each new release for the users

### ISSUE THREAD

**Issue by abdullah5490** [josephsl/wintenApps#36]
Hi there. I'm the regular user of your add-on, and really appreciate you all for such a nice work for win10 users out there. But here is a small suggestion from my side, that please provide the change log for each of the new release made to the add-on. It can be in ReadMe.ME section, or in add-on about/help pages. It would be much more helpful for your clients, to know your work and efforts in details about every release of the add-on. 
Thanks for reading,

**Comment by josephsl** [comment]
Hi, release notes can be found at https://github.com/josephsl/wintenapps/releases. Thanks.

**Comment by abdullah5490** [comment]
thanks alot. it helps too much. now close this issue
