### ISSUE TITLE
in skype uwp pressing end doesn'still reads skype message

### ISSUE THREAD

**Issue by derekriemer** [josephsl/wintenApps#37]
1. press end in the messages list

expected: shorter text

Actual: longer text, I.E. with "skype message"

**Comment by josephsl** [comment]
Hi, confirmed, looks like a height issue. Thanks.

**Comment by derekriemer** [comment]
height?

**Comment by josephsl** [comment]
Hi, I meant how the list view changes as you arrow through items. Thanks.

**Comment by josephsl** [comment]
Hi,

Is this still the case?

**Comment by derekriemer** [comment]
sometimes. If there's more than a few items to go through.

**Comment by josephsl** [comment]
No longer applicable as Skype of 2018 is not the same thing as Skype in 2020.
