### ISSUE TITLE
skype uwp alt+1 and friends break

### ISSUE THREAD

**Issue by derekriemer** [josephsl/wintenApps#38]
after I have selected a user for the first time and am in one of those edit fields, alt+1 stops working. I can't get str beyond that.

**Comment by josephsl** [comment]
Hi, sometimes, restarting NVDA helps, at other times, quitting and opening Skype again fixes this. Thanks.

**Comment by josephsl** [comment]
Hi,

I'd say it can be closed if no follow-ups are given. Thanks.

**Comment by derekriemer** [comment]
This is not broken anymore for me.

**Comment by josephsl** [comment]
Hi, if so, closing. Please reopen if it breaks again. Thanks.
