### ISSUE TITLE
Synchronize wintenApps simplified Chinese translation

### ISSUE THREAD

**Issue by dingpengyu** [josephsl/wintenApps#47]
Dear NVDA Translation Community
After a period of internal community testing, I am ready to synchronize the simplified Chinese translation of wintenApps to the NVDA translation community.
Finally, I thank every friend who gave me advice during the translation process.
[zh_cn.zip](https://github.com/josephsl/wintenApps/files/1941256/zh_cn.zip)

**Comment by josephsl** [comment]
Hi, for add-on translations, the best way to do this is using NVDA translations workflow. I’ll take care of this on your behalf prior to release of version 18.05 of this add-on. Thanks for the contribution and willingness to take this on. Thanks.
