### ISSUE TITLE
Suggestions close doesn't play when exiting settings.

### ISSUE THREAD

**Issue by derekriemer** [josephsl/wintenApps#5]
1. open settings.
2. type "account"
3. wait for the zoop sound.
4. alt+f4.
   What should happen? Suggestions closed (reverse xoop sound). No sound is played.

**Comment by josephsl** [comment]
Hi,

Confirmed. This is because Controller For event isn't fired when the app exits (technically, when it enters suspended state).

Thanks.

**Comment by josephsl** [comment]
Hi,

Still the case in 2021, although there's relaly nothing we can do about this. Closing.
