### ISSUE TITLE
Word 2019 last version duplicates NVDA attribute change notification when formatting text through keystrokes

### ISSUE THREAD

**Issue by ivnc** [josephsl/wintenApps#54]
See nvaccess/nvda#10950.
Could this issue be fixed by winTenApps, as with "delete back word"?

**Comment by josephsl** [comment]
Hi, I’ll generate a development snapshot today that should resolve this (I wish to talk to MS Word team about this…). Thanks.

**Comment by josephsl** [comment]
Hi, and should be resolved in recent releases.
