### ISSUE TITLE
Calender app: Announce name of day in month overview

### ISSUE THREAD

**Issue by NicklasTegner** [josephsl/wintenApps#57]
Hi there.

I was hoping it could be implemented, so NVDA would announce the day of week when going through the month overview in the calender.

As an example:
Right now NVDA says:

* 2. Maj 2021, no events.
* 3. Maj 2021, 1 events.

And I was hoping it could say something like.

* Sunday, 2. Maj 2021, no events.
* Monday, 3. Maj 2021, 1 events.

ps: I don't know if the english examples above is what it says, word for word, but I hope you get the idea.

If this is already possible, please do tell me. I've searched high and low, but don't think this is possible.

Take care

**Comment by josephsl** [comment]
Hi there, NVDA does announce the day I’m on (say, Sunday, May 2, 2021) I month view. Can you tell me steps to reproduce the problem so I can look into it for a possible release? Thanks.

**Comment by NicklasTegner** [comment]
Hi there...

# Steps to reproduce

1. Open calender.
2. Make sure the title of the current window is: "Month view - calendar"
3. You should have focus on the current day, if you go 1 right with the arrows, it says: "2. Maj 2021 - No events"
4. if you go 1 left again (so you go back to the current day) it says "Today, 1. Maj, 2021. 1 Event"

Due note that step 3 and 4 are just to illustrate how to get nvda to speak the dates.

### What it should do

Step 1 and 2 as above:

3. When arrowing 1 right, it should say: Sunday, 2. Maj 2021, No events.
4. And arrow 1 left (so on current day): Saturday 1. Maj, 2021, 1 Event.

**Comment by josephsl** [comment]
Hi, I see. Can you try with Narrator and see if it announces the day? On my system, NVDA does say, “Saturday, May 1, 2021” and “Sunday, May 2, 2021”. Thanks.

**Comment by NicklasTegner** [comment]
hi

Narrator does not say the day either...

**Comment by josephsl** [comment]
Hi, in this case, there’s really nothing NVDA can do, as it is up to Microsoft’s Mail and Calendar team to look into this. Sorry.

**Comment by NicklasTegner** [comment]
Do you have any idea, why it works on your system, but not mine?
Does Narrator say the name of the day on your system?

**Comment by josephsl** [comment]
Hi, yes, Narrator does announce the day on my system, and I’m using an English user interface. I think this is really up to Microsoft to fix this (might be a localization problem or something). Thanks.

**Comment by NicklasTegner** [comment]
I'm going to try switching my system to english, to try to figure out, if that's the problem or not.

**Comment by NicklasTegner** [comment]
Ok.I can confirm that this is a localisation error on Microsofts part.
When I have my stems language set to English, it announces the date ( Sunday, 2. Maj 2021) regardless of my NVDA language or preferences.

**Comment by josephsl** [comment]
Hi, in this case, I think it would be best to close this issue and send a feedback (via Feedback Hub app) to Microsoft. Thanks,
