### ISSUE TITLE
Bing Maps: issues with "IAccessible AttributeError"

### ISSUE THREAD

**Issue by josephsl** [josephsl/wintenApps#6]
Hi,

Several issues were observed in Maps app, all related to the following regression:

AttributeError: IAccessible object has no attribute "UIAElement"

Cause: over-zealous overlay class chooser that only checked for UIA elements, not knowing that an ancestor might be an IAccessible object.

This causes following issues:

* AttributeError exception logged.
* Cannot press TAB to move between various buttons (to reproduce, open Maps, go to Location button and press TAB).

Thanks.

**Comment by derekriemer** [comment]
Fixes

**Comment by derekriemer** [comment]
*fixed
