### ISSUE TITLE
Stops NVDA from reporting Osara in Reaper

### ISSUE THREAD

**Issue by Mike20001123** [josephsl/wintenApps#68]
# Symptoms: 
Osara messages in Reaper are no longer reported When Wintenapp Add-on is enabled. older version of Osara (2018.1) is not affected. 

# Version: 
Wintenapp 2022.2
Reaper 6.47
Osara 2022.1
NVDA2021.3
Windows 11 21H2 (x64) build 22000.527

**Comment by josephsl** [comment]
Hi, can you try with a development version of Windows App Essentials? To do so, go to NVDA community add-ons website (addons.nvda-project.org), select Windows App Essentials, select development version link, then install the dev version of the add-on and see if it changes anything. Also, I need a debug log please (see the comment I posted on OSARA repository on instructions). Thanks.

**Comment by Mike20001123** [comment]
Problem Solved 👍 

I disabled the notification report by chance and forgot to turn it back on, LOL. 

It is Very nice of you, thank you again for your instructions!

**Comment by josephsl** [comment]
You’re welcome as always.
