### ISSUE TITLE
Problem with translation system

### ISSUE THREAD

**Issue by nvdaes** [josephsl/wintenApps#91]
@josephsl , the l10n server has notified the following:

Running addon2svn for wintenApps
Already on 'stable'
Your branch is up to date with 'origin/stable'.
From github.com:nvdaaddons/wintenApps
   31ad7946..ad3337d5  stable     -> origin/stable
HEAD is now at ad3337d5 Add-on template: incorporate 2024.2 version follow-up such as custom braille translation tables (Windows App Essentials does not include them)
scons: Reading SConscript files ...
  File "/home/nvdal10n/mr/addons/wintenApps/sconstruct", line 193

                manifest += f"{'\n'.join(manifest_brailleTables)}\n"

                                                                    ^

SyntaxError: f-string expression part cannot include a backslash

mr addon2svn: command failed

So, translators are not receiving new strings for this add-on.
Cheers

**Comment by josephsl** [comment]
Hi, this is an add-on template issue – I’ll notify the add-ons community and come up with something. Thanks.

**Comment by josephsl** [comment]
Hi,

Traced to F string expression being invalid if backslash characters are included in the expression portion. This issue is resolved in Python 3.12, and a fix is provided in latest add-on template (commit b82cbfc).

Thanks for the initial report.
