### ISSUE TITLE
snappping to controls on win 11(feature request)

### ISSUE THREAD

**Issue by Glowing-Radiant** [josephsl/wintenApps#94]
hello.
I have a suggestion to make with regards to navigating on desktop.
when we tab around on desktop, we get strings like "pane  dragging" and silent treatment, is there a possibility of nvda snapping to controls while tabbing around on desktop?

**Comment by josephsl** [comment]
Hi,

Can you be more specific such as steps to reproduce, what NVDA is doing now, and what you want NVDA to do?

Thanks.

**Comment by Glowing-Radiant** [comment]
hi. right now if you want to go to staart button from desktop you tab 3 times. one time it says, pane  dragging, and one time nothing. I want it to snap to start button.

**Comment by josephsl** [comment]
Hi,

This is beyond NVDA's control as it has to do with Windows 11 taskbar controls. While you can't disable "pane dragging" control, you can turn off Widgets button (Settings/Personalization/Taskbar).

Thanks (closing as invalid/can't fix)
